site_name: Titor Technologies
site_url: https://titor.tech

docs_dir: docs

nav:
  - Home: index.md
  - Blog: blog/index.md
  # Tags: tags.md  # (hidden for now)
  - Projects:
      - Overview: projects/index.md
      - NWEB: projects/nweb.md
      - LNDY: projects/lndy.md
      - W3RK: projects/w3rk.md
      - Bastet: projects/bastet.md
      - Storm Dance: projects/storm-dance.md
  - Concepts:
      - Overview: concepts/index.md
      - Infrastructure: concepts/infra.md
      - Sustainability: concepts/sustainability.md
      - Gamification: concepts/gamification.md
      - Lindy: concepts/lindy.md
      - Cypherpunk: concepts/cypherpunk.md
      # Base economies: concepts/base-economies.md  # (removed for now)
      - Mechanical pantheon: concepts/mechanical-pantheon.md
  - Analysis:
      - Overview: analysis/index.md
      - Farcaster: analysis/farcaster.md
      - XMTP: analysis/xmtp.md
      - Bitcoin: analysis/bitcoin.md
      - Ethereum: analysis/ethereum.md
      - Solana: analysis/solana.md
      - EigenLayer: analysis/eigenlayer.md
      - LayerZero: analysis/layerzero.md
      - THORChain: analysis/thorchain.md
  - Forecasts:
      - Overview: forecasts/index.md
      - 2030 — AGI Era: forecasts/2030.md
      - 2040 — ASI Era: forecasts/2040.md
      - 2045 — Singularity: forecasts/2045.md

theme:
  name: material
  logo: img/titor.png

  palette:
    - scheme: slate
      primary: 'black'
      accent: 'deep orange'
      toggle:
        icon: material/brightness-4
        name: Switch to dark mode
    - scheme: default
      primary: 'black'
      accent: 'deep orange'
      toggle:
        icon: material/brightness-7
        name: Switch to light mode

extra_css:
  - css/custom-styles.css

extra_javascript:
  - js/expand-nav.js

plugins:
  - search
  - blog:
      blog_dir: blog
      post_dir: blog/posts
      post_url_format: "{date}/{slug}"
  - tags
  - rss:
      match_path: blog/posts/.*
      date_from_meta:
        as_creation: date
        as_update: date
      categories:
        - categories
        - tags
      use_material_blog: true
      rss_feed_enabled: true
      json_feed_enabled: false
      use_git: false

markdown_extensions:
  - meta
  - attr_list
  - md_in_html
  - pymdownx.superfences
